apiVersion: apps/v1
kind: Deployment
metadata:
  name: file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
        - name: file
          image: postique/file
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: file
spec:
  selector:
    app: file
  ports:
    - port: 6000
      name: grpc
      targetPort: 6000
  type: ClusterIP
