apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso
  template:
    metadata:
      labels:
        app: sso
    spec:
      containers:
        - name: sso
          image: postique/sso
          ports:
            - containerPort: 4000
              name: grpc
            - containerPort: 9091
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: sso
spec:
  selector:
    app: sso
  ports:
    - port: 4000
      name: grpc
      targetPort: 4000
    - port: 9091
      name: metrics
      targetPort: 9091
  type: ClusterIP
