server:
  port: 4000
  timeout: 10s

session:
  token_ttl: 48h
  secret: secretsecretsecr

postgres:
  host: postgres
  port: 5432
  user: postique
  password: postique
  database: sso
  ssl: disable

logger:
  mode: development
  disable_caller: false
  disable_stacktrace: false
  encoding: pretty
  level: info
