server:
  port: 4000
  timeout: 10s

session:
  token_ttl: 720h
  encryption_secret: 1234567890123456
  token_ed25519_private_key_path: .keys/private/access_token.pem
  token_ed25519_public_key_path: .keys/public/access_token.pem

postgres:
  host: postgres
  port: 5432
  user: postique
  password: postique
  database: sso
  ssl: disable

rmq:
  url: amqp://guest:guest@rabbitmq:5672
  user_queue: user_queue

logger:
  mode: development
  disable_caller: false
  disable_stacktrace: false
  encoding: pretty
  level: info
