export const ALLOWED_TAGS = [
  'a',
  'abbr',
  'b',
  'blockquote',
  'br',
  'caption',
  'code',
  'col',
  'colgroup',
  'dd',
  'del',
  'details',
  'dfn',
  'div',
  'dl',
  'dt',
  'em',
  'figcaption',
  'figure',
  'footer',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'header',
  'hr',
  'i',
  'img',
  'ins',
  'kbd',
  'label',
  'li',
  'mark',
  'nav',
  'ol',
  'p',
  'pre',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'section',
  'small',
  'span',
  'strong',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'tfoot',
  'th',
  'thead',
  'time',
  'tr',
  'u',
  'ul',
  'var',
];

export const ALLOWED_ATTRIBUTES = {
  '*': ['class', 'style', 'id', 'title', 'lang', 'dir'],
  a: ['href', 'name', 'target', 'rel'],
  img: ['src', 'alt', 'width', 'height', 'loading'],
  table: ['border', 'cellpadding', 'cellspacing', 'summary'],
  td: ['colspan', 'rowspan'],
  th: ['colspan', 'rowspan'],
  colgroup: ['span'],
  col: ['span'],
  time: ['datetime'],
};

export const ALLOWED_STYLES = {
  '*': {
    color: [
      /^#(?:[0-9a-fA-F]{3}){1,2}$/,
      /^rgb\((\d{1,3},\s*){2}\d{1,3}\)$/,
      /^rgba\((\d{1,3},\s*){3}(\d(\.\d+)?|1|0)\)$/,
    ],
    'background-color': [
      /^#(?:[0-9a-fA-F]{3}){1,2}$/,
      /^rgb\((\d{1,3},\s*){2}\d{1,3}\)$/,
      /^rgba\((\d{1,3},\s*){3}(\d(\.\d+)?|1|0)\)$/,
    ],
    'text-align': [/^left|right|center|justify$/],
    'font-weight': [/^normal|bold|bolder|lighter|[1-9]00$/],
    'font-style': [/^normal|italic|oblique$/],
    'text-decoration': [/^none|underline|line-through|overline$/],
  },
};
