.PHONY: app

env_dev:
	@echo "Starting app in development enviroment"
	@go run cmd/file/main.go --config=./config/development.yml

env_test:
	@echo "Starting app in testing enviroment"
	@go run cmd/file/main.go --config=./config/test.yml